name: legacy_gantt_protocol
description: A pure-Dart protocol synchronization library for Gantt Charts.
version: 1.0.6
repository: https://github.com/barneysspeedshop/legacy_gantt_protocol
environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
